# These are supported funding model platforms

github: [ad101-lab,TheBitOne]
custom: ["https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=rilesdk%40gmail.com&currency_code=USD&source=url","https://www.gofundme.com/f/hd-open-source-projects?utm_source=customer&utm_medium=copy_link-tip&utm_campaign=p_cp+share-sheet"]

